# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & test w local reg.

on:
  push:
    branches: [ debugworkflow ]
  pull_request:
    branches: [ debugworkflow ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Install local registry
      run: |
        /bin/bash -c "$(curl -fsSL https://data.scrc.uk/static/localregistry.sh)"
        ~/.fair/registry/scripts/start_fair_registry
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        export REGTOKEN=`cat ~/.fair/registry/token`
        export LOCALREG=FRESHASADAISY
        ./gradlew build
        echo "test/index.html"
        cat /home/runner/work/javaDataPipeline/javaDataPipeline/dataregistry/build/reports/tests/test/index.html
        echo "populatelocal:"
        cat /home/runner/work/javaDataPipeline/javaDataPipeline/dataregistry/build/reports/tests/test/classes/org.fairdatapipeline.dataregistry.restclient.populateLocal.html
    - uses: codecov/codecov-action@v2
      with:
        files: ./api/build/reports/jacoco/test/jacocoTestReport.xml,./dataregistry/build/reports/jacoco/test/jacocoTestReport.xml
