name: Deploy Javadoc

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          cache: gradle
          java-version: 11
          java-package: jdk+fx
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate Javadoc
        run: ./gradlew javadoc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          BRANCH: gh-pages
          CLEAN: true
          FOLDER: api/build/docs/javadoc
